### ISSUE TITLE
Create pull request in spring-boot main project

### ISSUE THREAD

**Issue by rajadilipkolli** [making/spring-boot-actuator-beansviz#1]
This is an awesome feature, can you create a pull request in spring-boot project? I think this will improve alot in visualisation

**Comment by rajadilipkolli** [comment]
If you provide me your nod I can try to create PR for this

**Comment by making** [comment]
To be honest I'm not sure adding [`guru.nidi:graphviz-java:0.1.0`](https://github.com/nidi3/graphviz-java) could be acceptable.
This uses native libraries to generate the graph fast. I tried it without native libraries (using Java 8's nashorn engine) and found it was too slow. Adding this dependency would be kind of risky.

@wilkinsona any comment will be appreciated.

**Comment by wilkinsona** [comment]
The native libraries themselves aren't a huge problem. 2.0 will add auto-configuration for Netty which uses native libraries, for example. However, I'm still not sure that this is something that we'd want to include in Spring Boot itself. It feels to me more like something that belongs in an IDE or Spring Boot Admin. STS already has such a feature for all Spring apps built on top of the framework's live beans view MBean.

**Comment by making** [comment]
@wilkinsona Thank you for your comment. I see.

@rajadilipkolli Sorry, i'm not going to create a pull request.
